from __future__ import annotations

from copy import deepcopy

from src.core.contracts import DispatchAssignment, new_event
from src.core.event_bus import EventBus
from src.core.project_manager import ProjectManager
from src.core.state_transaction import StateTransaction


def _render_file_content(target_file: str) -> str:
    if target_file == "helpers.py":
        return (
            "def helper() -> str:\n"
            "    return 'phase2-helper'\n"
        )
    if target_file == "app.py":
        return (
            "from helpers import helper\n\n"
            "def run() -> str:\n"
            "    return helper()\n"
        )
    return "# generated by phase2 worker\n"


async def worker_node(state: dict) -> dict:
    active_assignment = state.get("active_assignment")
    if active_assignment is None:
        return {
            "messages": [*state.get("messages", []), "worker skipped because no active assignment exists"],
        }

    assignment = DispatchAssignment.model_validate(active_assignment)
    project_id = state["project_id"]
    queue = deepcopy(state.get("worker_queue", []))
    file_registry = deepcopy(state.get("file_registry", {}))
    worker_status = deepcopy(state.get("worker_status", {}))
    worker_outputs = deepcopy(state.get("worker_outputs", {}))
    worker_failure_log = deepcopy(state.get("worker_failure_log", {}))
    target_file = assignment.target_file
    worker_id = assignment.worker_id

    try:
        file_registry[target_file] = "in_progress"
        worker_status[worker_id] = "working"
        async with StateTransaction(project_id) as transaction:
            persisted = transaction.state
            persisted.update(
                {
                    "file_registry": file_registry,
                    "worker_status": worker_status,
                }
            )
            transaction.state = persisted

        await ProjectManager().write_project_file(
            state["project_name"],
            target_file,
            _render_file_content(target_file),
        )

        for item in queue:
            if item["assignment"]["task_id"] == assignment.task_id:
                item["status"] = "done"
                break
        file_registry[target_file] = "done"
        worker_status[worker_id] = "idle"
        worker_outputs.setdefault(worker_id, []).append(target_file)

        await EventBus().emit(
            "sprint.worker_done",
            new_event(
                "sprint.worker_done",
                payload={
                    "task_id": assignment.task_id,
                    "worker_id": worker_id,
                    "target_file": target_file,
                },
                project_id=project_id,
                thread_id=assignment.thread_id,
                sprint_id=assignment.sprint_id,
                correlation_id=assignment.task_id,
            ).model_dump(),
        )
        updates = {
            "worker_queue": queue,
            "file_registry": file_registry,
            "worker_status": worker_status,
            "worker_outputs": worker_outputs,
            "active_assignment": None,
            "messages": [*state.get("messages", []), f"worker completed {target_file}"],
        }
    except Exception as exc:
        for item in queue:
            if item["assignment"]["task_id"] == assignment.task_id:
                item["status"] = "failed"
                item["validation_error"] = str(exc)
                break
        file_registry[target_file] = "failed"
        worker_status[worker_id] = "idle"
        worker_failure_log.setdefault(worker_id, []).append(
            {
                "task_id": assignment.task_id,
                "target_file": target_file,
                "error": str(exc),
            }
        )
        updates = {
            "worker_queue": queue,
            "file_registry": file_registry,
            "worker_status": worker_status,
            "worker_failure_log": worker_failure_log,
            "active_assignment": None,
            "errors": [
                *state.get("errors", []),
                {"type": "worker_failure", "target_file": target_file, "error": str(exc)},
            ],
            "messages": [*state.get("messages", []), f"worker failed {target_file}"],
        }

    async with StateTransaction(project_id) as transaction:
        persisted = transaction.state
        persisted.update(updates)
        transaction.state = persisted

    return updates
